theme: jekyll-theme-minimal
show_downloads: True
toc:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - subfolderitems:
      - page: About
        url: setup/about
      - page: Config Handlers
        url: setup/config_handlers
      - page: Config Layout
        url: setup/config_layout
      - page: New Actions
        url: setup/new_actions
      - page: Error codes
        url: setup/error_codes
  - title: YAML
    url: yaml
    subfolderitems:
      - page: Chooser UI
        url: yaml/chooser_ui
      - title: YAML Tips
        url: yaml/tips
  - title: Mailing List ğŸ’Œ
    url: https://groups.google.com/forum/#!forum/glazier-discuss
  - title: File A Bug ğŸ›
    url: https://github.com/google/glazier/issues/new
